
import MainLayout from '@/pages/Main';
import './globals.css'
import { Inter } from 'next/font/google'
import React from 'react';
import 'devextreme/dist/css/dx.light.css';


const inter = Inter({ subsets: ['latin'] })


// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} dx-viewport`}>

        <MainLayout child={children} />

      </body>
    </html>
  )
}
